web:
  image: nginx
  ports:
    - "8082:80"
  volumes:
    # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./mirror.conf:/etc/nginx/nginx.conf:ro
    - ./:/usr/share/nginx/html
  command: [nginx-debug, '-g', 'daemon off;']
